=== jlandic/foundry-fading-suns-4/schemas/classes.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "$ref": "./defs.schema.json#/itemType"
    },
    "name": {
      "type": "string"
    },
    "folder": {
      "type": [
        "string",
        "null"
      ]
    },
    "_id": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flags": {
      "type": "object",
      "additionalProperties": true
    },
    "_stats": {
      "type": "object",
      "additionalProperties": true
    },
    "ownership": {
      "type": "object",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "sort": {
      "type": "number"
    },
    "_key": {
      "type": "string"
    },
    "system": {
      "type": "object",
      "properties": {
        "characteristics": {
          "$ref": "./defs.schema.json#/characteristics"
        },
        "skills": {
          "$ref": "./defs.schema.json#/skills"
        },
        "description": {
          "type": "string"
        },
        "slug": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "perk": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "capabilities": {
          "$ref": "./defs.schema.json#/capabilities"
        },
        "perks": {
          "type": "array",
          "items": {
            "$ref": "./slugs.schema.json#/slug"
          }
        },
        "factions": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "al_malik",
              "brother_battle_faction",
              "charioteers",
              "decados",
              "engineers",
              "eskatonic_order",
              "far",
              "hawkwood",
              "hazat",
              "li_halan",
              "sanctuary_aeon",
              "scravers",
              "society_st_paulus",
              "temple_avesti",
              "the_dispossessed",
              "the_muster",
              "the_reeves",
              "urth_orthodox",
              "vagabonds",
              "vuldrok_barbarians",
              "drenjar",
              "lakol",
              "maghtaw",
              "rekgold",
              "skey",
              "zetol"
            ]
          }
        }
      },
      "required": [
        "slug",
        "description",
        "perk",
        "perks",
        "skills",
        "capabilities",
        "factions"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "type",
    "name",
    "_id",
    "system"
  ],
  "additionalProperties": true
}

=== jlandic/foundry-fading-suns-4/source/items/classes/vuldrok_u0D0WfLWHVZRgTi3.json
{
  "type": "class",
  "name": "vuldrok",
  "folder": null,
  "system": {
    "slug": "vuldrok",
    "description": "",
    "characteristics": [
      [
        {
          "slug": "dexterity",
          "value": 2
        },
        {
          "slug": "endurance",
          "value": 2
        },
        {
          "slug": "strength",
          "value": 2
        }
      ],
      [
        {
          "slug": "faith",
          "value": 1
        },
        {
          "slug": "will",
          "value": 1
        }
      ],
      [
        {
          "slug": "presence",
          "value": 2
        }
      ],
      [
        {
          "slug": "intuition",
          "value": 2
        }
      ]
    ],
    "skills": [
      [
        {
          "slug": "fight",
          "value": 2
        },
        {
          "slug": "melee",
          "value": 2
        },
        {
          "slug": "shoot",
          "value": 2
        }
      ],
      [
        {
          "slug": "arts",
          "value": 1
        }
      ],
      [
        {
          "slug": "charm",
          "value": 1
        },
        {
          "slug": "impress",
          "value": 1
        },
        {
          "slug": "perform",
          "value": 1
        }
      ],
      [
        {
          "slug": "survival",
          "value": 1
        }
      ],
      [
        {
          "slug": "vigor",
          "value": 1
        }
      ]
    ],
    "capabilities": [
      [
        "beastback",
        "oratory",
        "religion_lore_erdgheist"
      ],
      [
        "vuldrok_customs"
      ],
      [
        "military_weapons",
        "archery"
      ],
      [
        "read_speak_vuldrish"
      ],
      [
        "planet_lore_homeworld"
      ]
    ],
    "perk": "independant",
    "perks": [],
    "factions": [
      "maghtaw"
    ]
  },
  "_id": "GjRrQhnOK4dBvw5y",
  "img": "icons/skills/trades/academics-scribe-quill-gray.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760737853778,
    "modifiedTime": 1760795837666,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 300000,
  "_key": "!items!GjRrQhnOK4dBvw5y"
}

=== jlandic/foundry-fading-suns-4/source/items/classes/yeoman_FnNv5hYIyp4RLHvP.json
{
  "type": "class",
  "name": "yeoman",
  "folder": null,
  "system": {
    "slug": "yeoman",
    "description": "",
    "characteristics": [],
    "skills": [],
    "capabilities": [
      [
        "commons_customs",
        "cathedral_customs",
        "court_customs"
      ],
      [
        "planet_lore_homeworld"
      ],
      [
        "read_speak_urthish"
      ],
      [
        "special_any_capability"
      ],
      [
        "special_any_capability"
      ]
    ],
    "perk": "independant",
    "perks": [
      "house_holder",
      "martial_arts_graa",
      "martial_arts_iron_heel",
      "martial_arts_jox_kai_von",
      "martial_arts_koto",
      "martial_arts_shaidan",
      "military_rank",
      "nimble",
      "peasant_hero",
      "rep",
      "saints_blessing"
    ],
    "factions": [
      "the_dispossessed",
      "far",
      "society_st_paulus",
      "vuldrok_barbarians",
      "vagabonds"
    ]
  },
  "_id": "FnNv5hYIyp4RLHvP",
  "img": "icons/skills/trades/academics-scribe-quill-gray.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760737853778,
    "modifiedTime": 1760795837666,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 100000,
  "_key": "!items!FnNv5hYIyp4RLHvP"
}

=== jlandic/foundry-fading-suns-4/source/items/classes/priest_brother_battle_upbringing_Xe7uOb71oNAyNnmU.json
{
  "type": "class",
  "name": "priest_brother_battle_upbringing",
  "folder": null,
  "system": {
    "slug": "priest_brother_battle_upbringing",
    "description": "",
    "characteristics": [
      [
        {
          "slug": "strength",
          "value": 1
        }
      ],
      [
        {
          "slug": "dexterity",
          "value": 1
        }
      ],
      [
        {
          "slug": "endurance",
          "value": 1
        }
      ],
      [
        {
          "slug": "will",
          "value": 1
        }
      ],
      [
        {
          "slug": "faith",
          "value": 1
        }
      ]
    ],
    "skills": [
      [
        {
          "slug": "academia",
          "value": 1
        }
      ],
      [
        {
          "slug": "fight",
          "value": 1
        }
      ],
      [
        {
          "slug": "focus",
          "value": 1
        }
      ],
      [
        {
          "slug": "vigor",
          "value": 2
        }
      ]
    ],
    "capabilities": [
      [
        "combat_armor",
        "war_armor"
      ],
      [
        "cathedral_customs"
      ],
      [
        "read_speak_urthish"
      ],
      [
        "religion_lore"
      ]
    ],
    "perk": "inspiring",
    "perks": [
      "martial_arts_graa",
      "martial_arts_iron_heel",
      "martial_arts_jox_kai_von",
      "martial_arts_koto",
      "martial_arts_shaidan",
      "shepherd_of_the_flock",
      "holier_than_thou",
      "chartophylax",
      "witch_hunt",
      "condemn",
      "enlightened",
      "invigorate",
      "purge",
      "wise_one",
      "harmonize",
      "hierophant",
      "legate",
      "nimble",
      "landed",
      "riches",
      "inquisitorial_seal",
      "righteous_sermon",
      "retainer",
      "petition",
      "church_ordination"
    ],
    "factions": [
      "brother_battle_faction",
      "eskatonic_order",
      "sanctuary_aeon",
      "temple_avesti",
      "urth_orthodox"
    ]
  },
  "img": "icons/skills/trades/academics-scribe-quill-gray.webp",
  "effects": [],
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795837654,
    "modifiedTime": 1760795837666,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "_id": "Xe7uOb71oNAyNnmU",
  "sort": 200000,
  "_key": "!items!Xe7uOb71oNAyNnmU"
}
