=== jlandic/foundry-fading-suns-4/schemas/factions.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "$ref": "./defs.schema.json#/itemType"
    },
    "name": {
      "type": "string"
    },
    "folder": {
      "type": [
        "string",
        "null"
      ]
    },
    "_id": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flags": {
      "type": "object",
      "additionalProperties": true
    },
    "_stats": {
      "type": "object",
      "additionalProperties": true
    },
    "ownership": {
      "type": "object",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "sort": {
      "type": "number"
    },
    "_key": {
      "type": "string"
    },
    "system": {
      "type": "object",
      "properties": {
        "characteristics": {
          "$ref": "./defs.schema.json#/characteristics"
        },
        "skills": {
          "$ref": "./defs.schema.json#/skills"
        },
        "description": {
          "type": "string"
        },
        "slug": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "perk": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "curse": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "blessing": {
          "type": "array",
          "items": {
            "$ref": "./slugs.schema.json#/slug"
          }
        },
        "favoredCalling": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "equipment": {
          "$ref": "./slugs.schema.json#/slug"
        }
      },
      "required": [
        "slug",
        "description",
        "perk",
        "curse",
        "blessing",
        "characteristics",
        "skills",
        "equipment"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "type",
    "name",
    "_id",
    "system"
  ],
  "additionalProperties": true
}

=== jlandic/foundry-fading-suns-4/source/items/factions/sanctuary_aeon_Q8ZtZKWrA3qDgAYC.json
{
  "type": "faction",
  "name": "sanctuary_aeon",
  "folder": null,
  "system": {
    "description": "",
    "characteristics": [
      [
        {
          "name": "dexterity",
          "value": 2
        }
      ],
      [
        {
          "name": "faith",
          "value": 1
        },
        {
          "name": "intuition",
          "value": 1
        }
      ],
      [
        {
          "name": "presence",
          "value": 1
        }
      ],
      [
        {
          "name": "wits",
          "value": 1
        }
      ]
    ],
    "skills": [
      [
        {
          "name": "charm",
          "value": 1
        }
      ],
      [
        {
          "name": "empathy",
          "value": 1
        },
        {
          "name": "focus",
          "value": 1
        }
      ],
      [
        {
          "name": "academia",
          "value": 1
        },
        {
          "name": "arts",
          "value": 1
        },
        {
          "name": "perform",
          "value": 1
        }
      ],
      [
        {
          "name": "remedy",
          "value": 2
        }
      ]
    ],
    "perk": "church_ordination",
    "blessing": [
      "TODO"
    ],
    "curse": "TODO",
    "slug": "sanctuary_aeon",
    "equipment": "TODO",
    "favoredCalling": "TODO"
  },
  "_id": "Q8ZtZKWrA3qDgAYC",
  "img": "icons/sundries/flags/banner-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760897547556,
    "modifiedTime": 1760897547556,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!Q8ZtZKWrA3qDgAYC"
}

=== jlandic/foundry-fading-suns-4/source/items/factions/scravers_FTb2jKqjp3vDsdYr.json
{
  "type": "faction",
  "name": "scravers",
  "folder": null,
  "system": {
    "description": "",
    "characteristics": [
      [
        {
          "name": "dexterity",
          "value": 1
        },
        {
          "name": "strength",
          "value": 1
        }
      ],
      [
        {
          "name": "perception",
          "value": 1
        }
      ],
      [
        {
          "name": "presence",
          "value": 2
        }
      ],
      [
        {
          "name": "wits",
          "value": 1
        }
      ]
    ],
    "skills": [
      [
        {
          "name": "charm",
          "value": 1
        },
        {
          "name": "impress",
          "value": 1
        },
        {
          "name": "knavery",
          "value": 1
        }
      ],
      [
        {
          "name": "drive",
          "value": 1
        },
        {
          "name": "pilot",
          "value": 1
        }
      ],
      [
        {
          "name": "fight",
          "value": 1
        },
        {
          "name": "contact",
          "value": 1
        },
        {
          "name": "shoot",
          "value": 1
        }
      ],
      [
        {
          "name": "sleightofhand",
          "value": 1
        },
        {
          "name": "techredemption",
          "value": 1
        }
      ],
      [
        {
          "name": "intrusion",
          "value": 1
        },
        {
          "name": "observe",
          "value": 1
        }
      ]
    ],
    "perk": "guiild_commission",
    "blessing": [
      "TODO"
    ],
    "curse": "TODO",
    "slug": "scravers",
    "equipment": "TODO",
    "favoredCalling": "TODO"
  },
  "_id": "FTb2jKqjp3vDsdYr",
  "img": "icons/sundries/flags/banner-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760897547556,
    "modifiedTime": 1760897547556,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!FTb2jKqjp3vDsdYr"
}

=== jlandic/foundry-fading-suns-4/source/items/factions/hawkwood_mr7WBSoApi0KpCcB.json
{
  "type": "faction",
  "name": "hawkwood",
  "folder": null,
  "system": {
    "description": "",
    "characteristics": [
      [
        {
          "slug": "endurance",
          "value": 2
        },
        {
          "slug": "strength",
          "value": 2
        },
        {
          "slug": "wits",
          "value": 2
        }
      ],
      [
        {
          "slug": "faith",
          "value": 1
        },
        {
          "slug": "will",
          "value": 1
        }
      ],
      [
        {
          "slug": "presence",
          "value": 2
        }
      ]
    ],
    "skills": [
      [
        {
          "slug": "charm",
          "value": 2
        },
        {
          "slug": "impress",
          "value": 2
        }
      ],
      [
        {
          "slug": "melee",
          "value": 1
        },
        {
          "slug": "shoot",
          "value": 1
        }
      ],
      [
        {
          "slug": "academia",
          "value": 1
        }
      ],
      [
        {
          "slug": "focus",
          "value": 1
        },
        {
          "slug": "vigor",
          "value": 1
        }
      ]
    ],
    "perk": "noble_title",
    "blessing": [
      "unyielding"
    ],
    "curse": "prideful",
    "slug": "hawkwood",
    "equipment": "TODO",
    "favoredCalling": "commander",
    "capabilities": [
      [
        "military_weapons",
        "slug_guns",
        "energy_guns"
      ],
      [
        "faction_lore"
      ],
      [
        "beastback",
        "shipboard_operations",
        "warfare_lore"
      ]
    ]
  },
  "_id": "mr7WBSoApi0KpCcB",
  "img": "icons/sundries/flags/banner-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760897547556,
    "modifiedTime": 1760897547556,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!mr7WBSoApi0KpCcB"
}

=== jlandic/foundry-fading-suns-4/source/items/factions/engineers_X6lDwcdNR8ZKSq9G.json
{
  "type": "faction",
  "name": "engineers",
  "folder": null,
  "system": {
    "description": "",
    "characteristics": [
      [
        {
          "name": "dexterity",
          "value": 2
        }
      ],
      [
        {
          "name": "intuition",
          "value": 1
        }
      ],
      [
        {
          "name": "wits",
          "value": 2
        }
      ]
    ],
    "skills": [
      [
        {
          "name": "alchemy",
          "value": 1
        },
        {
          "name": "crafts",
          "value": 1
        },
        {
          "name": "focus",
          "value": 1
        }
      ],
      [
        {
          "name": "academia",
          "value": 1
        }
      ],
      [
        {
          "name": "interface",
          "value": 1
        }
      ],
      [
        {
          "name": "techredemption",
          "value": 2
        }
      ]
    ],
    "perk": "guiild_commission",
    "blessing": [
      "TODO"
    ],
    "curse": "TODO",
    "slug": "engineers",
    "equipment": "TODO",
    "favoredCalling": "TODO"
  },
  "_id": "X6lDwcdNR8ZKSq9G",
  "img": "icons/sundries/flags/banner-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760897547556,
    "modifiedTime": 1760897547556,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!X6lDwcdNR8ZKSq9G"
}

=== jlandic/foundry-fading-suns-4/source/items/factions/brother_battle_faction_KWzDNvfP9bzfZX3Y.json
{
  "type": "faction",
  "name": "brother_battle_faction",
  "folder": null,
  "system": {
    "description": "",
    "characteristics": [
      [
        {
          "name": "dexterity",
          "value": 1
        }
      ],
      [
        {
          "name": "endurance",
          "value": 1
        }
      ],
      [
        {
          "name": "faith",
          "value": 1
        }
      ],
      [
        {
          "name": "strength",
          "value": 2
        }
      ]
    ],
    "skills": [
      [
        {
          "name": "contact",
          "value": 1
        },
        {
          "name": "shoot",
          "value": 1
        }
      ],
      [
        {
          "name": "fight",
          "value": 1
        }
      ],
      [
        {
          "name": "focus",
          "value": 1
        },
        {
          "name": "impress",
          "value": 1
        },
        {
          "name": "survival",
          "value": 1
        }
      ],
      [
        {
          "name": "remedy",
          "value": 1
        }
      ],
      [
        {
          "name": "vigor",
          "value": 1
        }
      ]
    ],
    "perk": "church_ordination",
    "blessing": [
      "TODO"
    ],
    "curse": "TODO",
    "slug": "brother_battle_faction",
    "equipment": "TODO",
    "favoredCalling": "TODO"
  },
  "_id": "KWzDNvfP9bzfZX3Y",
  "img": "icons/sundries/flags/banner-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760897547556,
    "modifiedTime": 1760897547556,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!KWzDNvfP9bzfZX3Y"
}

=== jlandic/foundry-fading-suns-4/source/items/factions/the_muster_OrBOH294NpNLJlBJ.json
{
  "type": "faction",
  "name": "the_muster",
  "folder": null,
  "system": {
    "description": "",
    "characteristics": [
      [
        {
          "slug": "dexterity",
          "value": 2
        },
        {
          "slug": "endurance",
          "value": 2
        }
      ],
      [
        {
          "slug": "faith",
          "value": 1
        },
        {
          "slug": "will",
          "value": 1
        },
        {
          "slug": "presence",
          "value": 1
        }
      ],
      [
        {
          "slug": "strength",
          "value": 2
        }
      ]
    ],
    "skills": [
      [
        {
          "slug": "drive",
          "value": 1
        },
        {
          "slug": "pilot",
          "value": 1
        }
      ],
      [
        {
          "slug": "fight",
          "value": 1
        },
        {
          "slug": "melee",
          "value": 1
        }
      ],
      [
        {
          "slug": "impress",
          "value": 1
        }
      ],
      [
        {
          "slug": "techredemption",
          "value": 1
        },
        {
          "slug": "vigor",
          "value": 1
        }
      ],
      [
        {
          "slug": "shoot",
          "value": 1
        }
      ]
    ],
    "perk": "guild_commission",
    "blessing": [
      "bold"
    ],
    "curse": "callous",
    "slug": "the_muster",
    "equipment": "TODO",
    "favoredCalling": "mercenary",
    "capabilities": [
      [
        "faction_lore"
      ],
      [
        "special_any_equipment_capability"
      ],
      [
        "special_any_equipment_capability"
      ]
    ]
  },
  "_id": "OrBOH294NpNLJlBJ",
  "img": "icons/sundries/flags/banner-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760897547556,
    "modifiedTime": 1760897547556,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!OrBOH294NpNLJlBJ"
}
