=== jlandic/foundry-fading-suns-4/schemas/maneuver.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "$ref": "./defs.schema.json#/itemType"
    },
    "name": {
      "type": "string"
    },
    "folder": {
      "type": [
        "string",
        "null"
      ]
    },
    "_id": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flags": {
      "type": "object",
      "additionalProperties": true
    },
    "_stats": {
      "type": "object",
      "additionalProperties": true
    },
    "ownership": {
      "type": "object",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "sort": {
      "type": "number"
    },
    "_key": {
      "type": "string"
    },
    "system": {
      "type": "object",
      "properties": {
        "skill": {
          "type": "string",
          "enum": [
            "academia",
            "alchemy",
            "animalia",
            "arts",
            "charm",
            "crafts",
            "disguise",
            "drive",
            "empathy",
            "fight",
            "focus",
            "impress",
            "interface",
            "intrusion",
            "knavery",
            "melee",
            "observe",
            "perform",
            "pilot",
            "remedy",
            "shoot",
            "sleightofhand",
            "sneak",
            "survival",
            "techredemption",
            "vigor"
          ]
        },
        "characteristic": {
          "type": "string",
          "enum": [
            "strength",
            "dexterity",
            "endurance",
            "wits",
            "perception",
            "will",
            "presence",
            "intuition",
            "faith",
            "special_distribute_points"
          ]
        },
        "playScale": {
          "type": "string",
          "enum": [
            "present_tense",
            "instantaneous",
            "narrated"
          ]
        },
        "type": {
          "type": "string",
          "enum": [
            "action",
            "combat",
            "defense",
            "influence",
            "influence_persuasion",
            "influence_coercion"
          ]
        },
        "description": {
          "type": "string"
        },
        "goalModifier": {
          "type": "string",
          "enum": [
            "none",
            "melee_weapon",
            "ranged_weapon"
          ]
        },
        "slug": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "noVP": {
          "type": "boolean"
        },
        "actionType": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "primary",
              "reflexive_primary",
              "secondary",
              "reflexive_secondary",
              "movement"
            ]
          }
        }
      },
      "required": [
        "type",
        "playScale",
        "goalModifier",
        "actionType",
        "slug",
        "noVP"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "type",
    "name",
    "_id",
    "system"
  ],
  "additionalProperties": true
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/program_d3uaLai7dbLymxrI.json
{
  "type": "maneuver",
  "name": "program",
  "folder": null,
  "system": {
    "slug": "program",
    "type": "action",
    "skill": "interface",
    "characteristic": "wits",
    "goalModifier": "none",
    "actionType": [],
    "playScale": "narrated",
    "noVP": false
  },
  "_id": "d3uaLai7dbLymxrI",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!d3uaLai7dbLymxrI"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/evaluate_artwork_detect_fake_rRVcHGgXoLC0mqYe.json
{
  "type": "maneuver",
  "name": "evaluate_artwork_detect_fake",
  "folder": null,
  "system": {
    "slug": "evaluate_artwork_detect_fake",
    "type": "action",
    "skill": "arts",
    "characteristic": "perception",
    "goalModifier": "none",
    "actionType": [],
    "playScale": "present_tense",
    "noVP": false
  },
  "_id": "rRVcHGgXoLC0mqYe",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!rRVcHGgXoLC0mqYe"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/concentrate_PvWKW1bt5BQ9HUhc.json
{
  "type": "maneuver",
  "name": "concentrate",
  "folder": null,
  "system": {
    "slug": "concentrate",
    "type": "action",
    "skill": "focus",
    "characteristic": "will",
    "goalModifier": "none",
    "actionType": [],
    "playScale": "present_tense",
    "noVP": false
  },
  "_id": "PvWKW1bt5BQ9HUhc",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!PvWKW1bt5BQ9HUhc"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/ride_Iq8PCWnaHhmH3mi5.json
{
  "type": "maneuver",
  "name": "ride",
  "folder": null,
  "system": {
    "slug": "ride",
    "type": "action",
    "skill": "vigor",
    "characteristic": "presence",
    "goalModifier": "none",
    "actionType": [],
    "playScale": "instantaneous",
    "noVP": true
  },
  "_id": "Iq8PCWnaHhmH3mi5",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!Iq8PCWnaHhmH3mi5"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/befriend_zDNKro8eJo4NNyxi.json
{
  "type": "maneuver",
  "name": "befriend",
  "folder": null,
  "system": {
    "slug": "befriend",
    "type": "influence_persuasion",
    "skill": "charm",
    "characteristic": "presence",
    "goalModifier": "none",
    "actionType": [
      "primary"
    ],
    "playScale": "instantaneous",
    "noVP": false
  },
  "_id": "zDNKro8eJo4NNyxi",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!zDNKro8eJo4NNyxi"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/haggle_knavery_JjacURAUnzqM4mZp.json
{
  "type": "maneuver",
  "name": "haggle_knavery",
  "folder": null,
  "system": {
    "slug": "haggle_knavery",
    "type": "influence_persuasion",
    "skill": "knavery",
    "characteristic": "presence",
    "goalModifier": "none",
    "actionType": [
      "primary"
    ],
    "playScale": "instantaneous",
    "noVP": false
  },
  "_id": "JjacURAUnzqM4mZp",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!JjacURAUnzqM4mZp"
}
