=== jlandic/foundry-fading-suns-4/schemas/maneuver.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "$ref": "./defs.schema.json#/itemType"
    },
    "name": {
      "type": "string"
    },
    "folder": {
      "type": [
        "string",
        "null"
      ]
    },
    "_id": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flags": {
      "type": "object",
      "additionalProperties": true
    },
    "_stats": {
      "type": "object",
      "additionalProperties": true
    },
    "ownership": {
      "type": "object",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "sort": {
      "type": "number"
    },
    "_key": {
      "type": "string"
    },
    "system": {
      "type": "object",
      "properties": {
        "skill": {
          "type": "string",
          "enum": [
            "academia",
            "alchemy",
            "animalia",
            "arts",
            "charm",
            "crafts",
            "disguise",
            "drive",
            "empathy",
            "fight",
            "focus",
            "impress",
            "interface",
            "intrusion",
            "knavery",
            "melee",
            "observe",
            "perform",
            "pilot",
            "remedy",
            "shoot",
            "sleightofhand",
            "sneak",
            "survival",
            "techredemption",
            "vigor"
          ]
        },
        "characteristic": {
          "type": "string",
          "enum": [
            "strength",
            "dexterity",
            "endurance",
            "wits",
            "perception",
            "will",
            "presence",
            "intuition",
            "faith",
            "special_distribute_points"
          ]
        },
        "playScale": {
          "type": "string",
          "enum": [
            "present_tense",
            "instantaneous",
            "narrated"
          ]
        },
        "type": {
          "type": "string",
          "enum": [
            "action",
            "combat",
            "defense",
            "influence",
            "influence_persuasion",
            "influence_coercion"
          ]
        },
        "description": {
          "type": "string"
        },
        "goalModifier": {
          "type": "string",
          "enum": [
            "none",
            "melee_weapon",
            "ranged_weapon"
          ]
        },
        "slug": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "noVP": {
          "type": "boolean"
        },
        "actionType": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "primary",
              "reflexive_primary",
              "secondary",
              "reflexive_secondary",
              "movement"
            ]
          }
        }
      },
      "required": [
        "type",
        "playScale",
        "goalModifier",
        "actionType",
        "slug",
        "noVP"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "type",
    "name",
    "_id",
    "system"
  ],
  "additionalProperties": true
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/impersonate_alien_qjI6N1J0rNsf0UCd.json
{
  "type": "maneuver",
  "name": "impersonate_alien",
  "folder": null,
  "system": {
    "slug": "impersonate_alien",
    "type": "action",
    "skill": "disguise",
    "characteristic": "presence",
    "goalModifier": "none",
    "actionType": [],
    "playScale": "narrated",
    "noVP": false
  },
  "_id": "qjI6N1J0rNsf0UCd",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!qjI6N1J0rNsf0UCd"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/aim_long_ZrSOvRblih7PneRv.json
{
  "type": "maneuver",
  "name": "aim_long",
  "folder": null,
  "system": {
    "slug": "aim_long",
    "type": "combat",
    "skill": "shoot",
    "characteristic": "perception",
    "goalModifier": "ranged_weapon",
    "actionType": [
      "primary"
    ],
    "playScale": "instantaneous",
    "noVP": false
  },
  "_id": "ZrSOvRblih7PneRv",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!ZrSOvRblih7PneRv"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/ram_aowjtysgJl2Yzwxd.json
{
  "type": "maneuver",
  "name": "ram",
  "folder": null,
  "system": {
    "slug": "ram",
    "type": "action",
    "skill": "drive",
    "characteristic": "dexterity",
    "goalModifier": "none",
    "actionType": [
      "primary"
    ],
    "playScale": "instantaneous",
    "noVP": false
  },
  "_id": "aowjtysgJl2Yzwxd",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!aowjtysgJl2Yzwxd"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/encourage_HF9bmmA2OrBXZ2b0.json
{
  "type": "maneuver",
  "name": "encourage",
  "folder": null,
  "system": {
    "slug": "encourage",
    "type": "defense",
    "skill": "impress",
    "characteristic": "faith",
    "goalModifier": "none",
    "actionType": [
      "reflexive_primary"
    ],
    "playScale": "instantaneous",
    "noVP": false
  },
  "_id": "HF9bmmA2OrBXZ2b0",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!HF9bmmA2OrBXZ2b0"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/forge_artwork_dexterity_jZXWsIsWfdS6LuBa.json
{
  "type": "maneuver",
  "name": "forge_artwork_dexterity",
  "folder": null,
  "system": {
    "slug": "forge_artwork_dexterity",
    "type": "action",
    "skill": "arts",
    "characteristic": "dexterity",
    "goalModifier": "none",
    "actionType": [],
    "playScale": "present_tense",
    "noVP": false
  },
  "_id": "jZXWsIsWfdS6LuBa",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!jZXWsIsWfdS6LuBa"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/stunt_piloting_XHk2Hs9TXJiWGXr5.json
{
  "type": "maneuver",
  "name": "stunt_piloting",
  "folder": null,
  "system": {
    "slug": "stunt_piloting",
    "type": "action",
    "skill": "pilot",
    "characteristic": "intuition",
    "goalModifier": "none",
    "actionType": [
      "primary"
    ],
    "playScale": "instantaneous",
    "noVP": false
  },
  "_id": "XHk2Hs9TXJiWGXr5",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!XHk2Hs9TXJiWGXr5"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/hack_and_slash_6HD5Q98R9EPH12vJ.json
{
  "type": "maneuver",
  "name": "hack_and_slash",
  "folder": null,
  "system": {
    "slug": "hack_and_slash",
    "type": "combat",
    "skill": "melee",
    "characteristic": "strength",
    "goalModifier": "melee_weapon",
    "actionType": [
      "primary"
    ],
    "playScale": "instantaneous",
    "noVP": false
  },
  "_id": "6HD5Q98R9EPH12vJ",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!6HD5Q98R9EPH12vJ"
}

=== jlandic/foundry-fading-suns-4/source/items/maneuvers/repair_1XcdPZqfho4s1M8C.json
{
  "type": "maneuver",
  "name": "repair",
  "folder": null,
  "system": {
    "slug": "repair",
    "type": "action",
    "skill": "drive",
    "characteristic": "wits",
    "goalModifier": "none",
    "actionType": [
      "primary"
    ],
    "playScale": "instantaneous",
    "noVP": false
  },
  "_id": "1XcdPZqfho4s1M8C",
  "img": "icons/magic/symbols/cog-orange-red.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1761235912183,
    "modifiedTime": 1761235912183,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!1XcdPZqfho4s1M8C"
}
