=== jlandic/foundry-fading-suns-4/schemas/perks.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "$ref": "./defs.schema.json#/itemType"
    },
    "name": {
      "type": "string"
    },
    "folder": {
      "type": [
        "string",
        "null"
      ]
    },
    "_id": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flags": {
      "type": "object",
      "additionalProperties": true
    },
    "_stats": {
      "type": "object",
      "additionalProperties": true
    },
    "ownership": {
      "type": "object",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "sort": {
      "type": "number"
    },
    "_key": {
      "type": "string"
    },
    "system": {
      "type": "object",
      "properties": {
        "sourceType": {
          "type": "string",
          "enum": [
            "class",
            "calling",
            "species"
          ]
        },
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "austerity",
            "birthright",
            "cyberdevice",
            "power",
            "privilege",
            "verve"
          ]
        },
        "preconditions": {
          "$ref": "./defs.schema.json#/preconditions"
        },
        "description": {
          "type": "string"
        },
        "benefice": {
          "type": "string"
        },
        "slug": {
          "$ref": "./slugs.schema.json#/slug"
        }
      },
      "required": [
        "sourceType",
        "type",
        "slug",
        "description",
        "preconditions"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "type",
    "name",
    "_id",
    "system"
  ],
  "additionalProperties": true
}

=== jlandic/foundry-fading-suns-4/source/items/perks/criminal_archive_access_xtw0nkhLCQXeAWOa.json
{
  "type": "perk",
  "name": "criminal_archive_access",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "privilege",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "bounty_hunter"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "detective"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "scribe"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "criminal_archive_access"
  },
  "_id": "xtw0nkhLCQXeAWOa",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 22600000,
  "_key": "!items!xtw0nkhLCQXeAWOa"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/guild_commission_3_90UWdCbOtLxj2rMP.json
{
  "type": "perk",
  "name": "guild_commission_3",
  "folder": null,
  "system": {
    "slug": "guild_commission_3",
    "description": "",
    "benefice": "",
    "preconditions": [
      [
        {
          "type": "class",
          "slug": "merchant"
        }
      ]
    ],
    "sourceType": "class",
    "type": "privilege",
    "previousLevel": "guild_commission_2",
    "nextLevel": "guild_commission_4"
  },
  "_id": "90UWdCbOtLxj2rMP",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760897715440,
    "modifiedTime": 1760897715440,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!90UWdCbOtLxj2rMP"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/fencing_kraxi_2_gUjWCydtqvhopez4.json
{
  "name": "fencing_kraxi_2",
  "type": "perk",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "system": {
    "slug": "fencing_kraxi_2",
    "description": "",
    "sourceType": "class",
    "type": "ability",
    "benefice": "",
    "preconditions": [
      [
        {
          "type": "faction",
          "slug": "decados"
        },
        {
          "type": "class",
          "slug": "merchant"
        },
        {
          "type": "species",
          "slug": "ukar"
        }
      ]
    ],
    "previousLevel": "fencing_kraxi"
  },
  "effects": [],
  "folder": null,
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760801384449,
    "modifiedTime": 1760801384449,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "_id": "gUjWCydtqvhopez4",
  "sort": 0,
  "_key": "!items!gUjWCydtqvhopez4"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/intruder_RqX9CcI2FA9fBAth.json
{
  "type": "perk",
  "name": "intruder",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "ability",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "reclaimer"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "thief"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "intruder"
  },
  "_id": "RqX9CcI2FA9fBAth",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 11300000,
  "_key": "!items!RqX9CcI2FA9fBAth"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/reeve_advocate_gXtIbAZjZow1C7Mw.json
{
  "type": "perk",
  "name": "reeve_advocate",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "privilege",
    "preconditions": [
      [
        {
          "type": "perk",
          "slug": "riches",
          "value": "2"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "reeve_advocate"
  },
  "_id": "gXtIbAZjZow1C7Mw",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 16300000,
  "_key": "!items!gXtIbAZjZow1C7Mw"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/witch_hunt_llZLYebFW67AgEPS.json
{
  "type": "perk",
  "name": "witch_hunt",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "privilege",
    "preconditions": [
      [
        {
          "type": "class",
          "slug": "priest"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "inquisitor"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "witch_hunt"
  },
  "_id": "llZLYebFW67AgEPS",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 18200000,
  "_key": "!items!llZLYebFW67AgEPS"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/gossip_network_Bv0jhNTbWq6hZWgz.json
{
  "type": "perk",
  "name": "gossip_network",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "privilege",
    "preconditions": [
      [
        {
          "type": "special",
          "slug": "one_plus_customs"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "gossip_network"
  },
  "_id": "Bv0jhNTbWq6hZWgz",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 4300000,
  "_key": "!items!Bv0jhNTbWq6hZWgz"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/martial_arts_graa_1xpqcFADszqWPZgF.json
{
  "name": "martial_arts_graa",
  "type": "perk",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "system": {
    "slug": "martial_arts_graa",
    "description": "",
    "sourceType": "class",
    "type": "ability",
    "benefice": "",
    "preconditions": [
      [
        {
          "type": "species",
          "slug": "vorox"
        }
      ]
    ],
    "nextLevel": "martial_arts_graa_2"
  },
  "effects": [],
  "folder": null,
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760801390235,
    "modifiedTime": 1760801390235,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "_id": "1xpqcFADszqWPZgF",
  "sort": 0,
  "_key": "!items!1xpqcFADszqWPZgF"
}
