=== jlandic/foundry-fading-suns-4/schemas/perks.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "$ref": "./defs.schema.json#/itemType"
    },
    "name": {
      "type": "string"
    },
    "folder": {
      "type": [
        "string",
        "null"
      ]
    },
    "_id": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flags": {
      "type": "object",
      "additionalProperties": true
    },
    "_stats": {
      "type": "object",
      "additionalProperties": true
    },
    "ownership": {
      "type": "object",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "sort": {
      "type": "number"
    },
    "_key": {
      "type": "string"
    },
    "system": {
      "type": "object",
      "properties": {
        "sourceType": {
          "type": "string",
          "enum": [
            "class",
            "calling",
            "species"
          ]
        },
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "austerity",
            "birthright",
            "cyberdevice",
            "power",
            "privilege",
            "verve"
          ]
        },
        "preconditions": {
          "$ref": "./defs.schema.json#/preconditions"
        },
        "description": {
          "type": "string"
        },
        "benefice": {
          "type": "string"
        },
        "slug": {
          "$ref": "./slugs.schema.json#/slug"
        }
      },
      "required": [
        "sourceType",
        "type",
        "slug",
        "description",
        "preconditions"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "type",
    "name",
    "_id",
    "system"
  ],
  "additionalProperties": true
}

=== jlandic/foundry-fading-suns-4/source/items/perks/trendsetter_y1BrMAyaQ9SxFAcS.json
{
  "type": "perk",
  "name": "trendsetter",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "privilege",
    "preconditions": [
      [
        {
          "type": "capability",
          "slug": "commons_customs"
        }
      ],
      [
        {
          "type": "capability",
          "slug": "court_customs"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "trendsetter"
  },
  "_id": "y1BrMAyaQ9SxFAcS",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 22800000,
  "_key": "!items!y1BrMAyaQ9SxFAcS"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/fencing_serpentis_jQ1PjedsNOwLkEAD.json
{
  "name": "fencing_serpentis",
  "type": "perk",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "system": {
    "slug": "fencing_serpentis",
    "description": "",
    "sourceType": "class",
    "type": "ability",
    "benefice": "",
    "preconditions": [
      [
        {
          "type": "class",
          "slug": "noble"
        }
      ],
      [
        {
          "type": "special",
          "slug": "performing_arts_dancing"
        }
      ]
    ],
    "nextLevel": "fencing_serpentis_2"
  },
  "effects": [],
  "folder": null,
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760801385161,
    "modifiedTime": 1760801385161,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "_id": "jQ1PjedsNOwLkEAD",
  "sort": 0,
  "_key": "!items!jQ1PjedsNOwLkEAD"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/tend_the_flock_DZKoO83ilhoPEX9b.json
{
  "type": "perk",
  "name": "tend_the_flock",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "verve",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "friar"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "tend_the_flock"
  },
  "_id": "DZKoO83ilhoPEX9b",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 5000000,
  "_key": "!items!DZKoO83ilhoPEX9b"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/secret_agent_HQzESfAXbHeOPkMm.json
{
  "type": "perk",
  "name": "secret_agent",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "privilege",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "spy_priest"
        },
        {
          "type": "calling",
          "slug": "spy_noble"
        },
        {
          "type": "calling",
          "slug": "spy_merchant"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "secret_agent"
  },
  "_id": "HQzESfAXbHeOPkMm",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 6700000,
  "_key": "!items!HQzESfAXbHeOPkMm"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/fencing_torero_2_PgZLrngXiztYURlF.json
{
  "name": "fencing_torero_2",
  "type": "perk",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "system": {
    "slug": "fencing_torero_2",
    "description": "",
    "sourceType": "class",
    "type": "ability",
    "benefice": "",
    "preconditions": [
      [
        {
          "type": "class",
          "slug": "noble"
        }
      ]
    ],
    "previousLevel": "fencing_torero"
  },
  "effects": [],
  "folder": null,
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760801387763,
    "modifiedTime": 1760801387763,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "_id": "PgZLrngXiztYURlF",
  "sort": 0,
  "_key": "!items!PgZLrngXiztYURlF"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/triumphant_return_fMeXInfG7Ra3bIzC.json
{
  "type": "perk",
  "name": "triumphant_return",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "ability",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "incognito"
        },
        {
          "type": "perk",
          "slug": "loyalist"
        }
      ],
      [
        {
          "type": "perk",
          "slug": "mentor"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "triumphant_return"
  },
  "_id": "fMeXInfG7Ra3bIzC",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 15600000,
  "_key": "!items!fMeXInfG7Ra3bIzC"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/armor_of_sanctity_0pHTQJDnKx1Uempc.json
{
  "type": "perk",
  "name": "armor_of_sanctity",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "privilege",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "friar"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "armor_of_sanctity"
  },
  "_id": "0pHTQJDnKx1Uempc",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 200000,
  "_key": "!items!0pHTQJDnKx1Uempc"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/riches_5_QSdX2rQ7OoVx7XZZ.json
{
  "name": "riches_5",
  "type": "perk",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "system": {
    "slug": "riches_5",
    "description": "",
    "sourceType": "class",
    "type": "privilege",
    "benefice": "",
    "preconditions": [
      [
        {
          "type": "class",
          "slug": "noble"
        }
      ],
      [
        {
          "type": "class",
          "slug": "priest"
        }
      ],
      [
        {
          "type": "class",
          "slug": "merchant"
        }
      ]
    ],
    "previousLevel": "riches_4"
  },
  "effects": [],
  "folder": null,
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760801404212,
    "modifiedTime": 1760801404212,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "_id": "QSdX2rQ7OoVx7XZZ",
  "sort": 0,
  "_key": "!items!QSdX2rQ7OoVx7XZZ"
}
