=== jlandic/foundry-fading-suns-4/schemas/perks.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "$ref": "./defs.schema.json#/itemType"
    },
    "name": {
      "type": "string"
    },
    "folder": {
      "type": [
        "string",
        "null"
      ]
    },
    "_id": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flags": {
      "type": "object",
      "additionalProperties": true
    },
    "_stats": {
      "type": "object",
      "additionalProperties": true
    },
    "ownership": {
      "type": "object",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "sort": {
      "type": "number"
    },
    "_key": {
      "type": "string"
    },
    "system": {
      "type": "object",
      "properties": {
        "sourceType": {
          "type": "string",
          "enum": [
            "class",
            "calling",
            "species"
          ]
        },
        "type": {
          "type": "string",
          "enum": [
            "ability",
            "austerity",
            "birthright",
            "cyberdevice",
            "power",
            "privilege",
            "verve"
          ]
        },
        "preconditions": {
          "$ref": "./defs.schema.json#/preconditions"
        },
        "description": {
          "type": "string"
        },
        "benefice": {
          "type": "string"
        },
        "slug": {
          "$ref": "./slugs.schema.json#/slug"
        }
      },
      "required": [
        "sourceType",
        "type",
        "slug",
        "description",
        "preconditions"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "type",
    "name",
    "_id",
    "system"
  ],
  "additionalProperties": true
}

=== jlandic/foundry-fading-suns-4/source/items/perks/savings_YcK50oE3tz2BEbV8.json
{
  "type": "perk",
  "name": "savings",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "verve",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "banker"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "thief"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "trader"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "savings"
  },
  "_id": "YcK50oE3tz2BEbV8",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 13600000,
  "_key": "!items!YcK50oE3tz2BEbV8"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/dance_of_destruction_F8pz0KYjiG7fG7FP.json
{
  "type": "perk",
  "name": "dance_of_destruction",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "ability",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "duelist"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "dance_of_destruction"
  },
  "_id": "F8pz0KYjiG7fG7FP",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 5900000,
  "_key": "!items!F8pz0KYjiG7fG7FP"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/scent_of_the_witch_Zmo6vDx1dqgpM3u8.json
{
  "type": "perk",
  "name": "scent_of_the_witch",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "ability",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "inquisitor"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "occultist"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "psychic"
        }
      ],
      [
        {
          "type": "calling",
          "slug": "theurgist"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "scent_of_the_witch"
  },
  "_id": "Zmo6vDx1dqgpM3u8",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 14100000,
  "_key": "!items!Zmo6vDx1dqgpM3u8"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/oral_memory_DdhIYOSZX988uDz5.json
{
  "type": "perk",
  "name": "oral_memory",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "ability",
    "preconditions": [
      [
        {
          "type": "species",
          "slug": "obun"
        },
        {
          "type": "special",
          "slug": "obun_education"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "oral_memory"
  },
  "_id": "DdhIYOSZX988uDz5",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 5100000,
  "_key": "!items!DdhIYOSZX988uDz5"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/saint_lextius_blessing_vkJmncC8UzyrXnRc.json
{
  "type": "perk",
  "name": "saint_lextius_blessing",
  "folder": null,
  "system": {
    "sourceType": "class",
    "type": "verve",
    "preconditions": [
      [
        {
          "type": "class",
          "slug": "noble"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "saint_lextius_blessing"
  },
  "_id": "vkJmncC8UzyrXnRc",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 21800000,
  "_key": "!items!vkJmncC8UzyrXnRc"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/gambler_tansxbEfcZ0j0Q6B.json
{
  "type": "perk",
  "name": "gambler",
  "folder": null,
  "system": {
    "sourceType": "class",
    "type": "ability",
    "preconditions": [
      [
        {
          "type": "class",
          "slug": "merchant"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "gambler"
  },
  "_id": "tansxbEfcZ0j0Q6B",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 20800000,
  "_key": "!items!tansxbEfcZ0j0Q6B"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/martial_arts_iron_heel_NK6aKAB9HhSxJZ9j.json
{
  "name": "martial_arts_iron_heel",
  "type": "perk",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "system": {
    "slug": "martial_arts_iron_heel",
    "description": "",
    "sourceType": "class",
    "type": "ability",
    "benefice": "",
    "preconditions": [
      [
        {
          "type": "faction",
          "slug": "the_muster"
        },
        {
          "type": "calling",
          "slug": "bounty_hunter"
        },
        {
          "type": "calling",
          "slug": "chainer"
        },
        {
          "type": "calling",
          "slug": "mercenary"
        }
      ]
    ],
    "nextLevel": "martial_arts_iron_heel_2"
  },
  "effects": [],
  "folder": null,
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760801391856,
    "modifiedTime": 1760801391856,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "_id": "NK6aKAB9HhSxJZ9j",
  "sort": 0,
  "_key": "!items!NK6aKAB9HhSxJZ9j"
}

=== jlandic/foundry-fading-suns-4/source/items/perks/trouble_magnet_hF9ZLeckH3Xaavoe.json
{
  "type": "perk",
  "name": "trouble_magnet",
  "folder": null,
  "system": {
    "sourceType": "calling",
    "type": "ability",
    "preconditions": [
      [
        {
          "type": "calling",
          "slug": "ronin"
        }
      ]
    ],
    "description": "",
    "benefice": "",
    "slug": "trouble_magnet"
  },
  "_id": "hF9ZLeckH3Xaavoe",
  "img": "icons/magic/control/buff-flight-wings-blue.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760795828230,
    "modifiedTime": 1760801372488,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 16700000,
  "_key": "!items!hF9ZLeckH3Xaavoe"
}
