=== jlandic/foundry-fading-suns-4/schemas/species.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type": {
      "$ref": "./defs.schema.json#/itemType"
    },
    "name": {
      "type": "string"
    },
    "folder": {
      "type": [
        "string",
        "null"
      ]
    },
    "_id": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "effects": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "flags": {
      "type": "object",
      "additionalProperties": true
    },
    "_stats": {
      "type": "object",
      "additionalProperties": true
    },
    "ownership": {
      "type": "object",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "sort": {
      "type": "number"
    },
    "_key": {
      "type": "string"
    },
    "system": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "slug": {
          "$ref": "./slugs.schema.json#/slug"
        },
        "size": {
          "type": "number"
        },
        "speed": {
          "type": "object",
          "properties": {
            "twoLegs": {
              "type": "number"
            },
            "fourLegs": {
              "type": "number"
            },
            "sixLegs": {
              "type": "number"
            }
          },
          "required": [
            "twoLegs"
          ]
        },
        "birthrights": {
          "type": "array",
          "items": {
            "$ref": "./slugs.schema.json#/slug"
          }
        },
        "conditionedBirthrights": {
          "type": "array",
          "items": {
            "$ref": "./slugs.schema.json#/slug"
          }
        },
        "perks": {
          "type": "array",
          "items": {
            "$ref": "./slugs.schema.json#/slug"
          }
        },
        "capabilities": {
          "$ref": "./defs.schema.json#/capabilities"
        },
        "maneuvers": {
          "type": "array",
          "items": {
            "$ref": "./slugs.schema.json#/slug"
          }
        },
        "powerSkills": {
          "$ref": "./defs.schema.json#/powerSkills"
        }
      },
      "required": [
        "slug",
        "description",
        "size",
        "speed",
        "birthrights",
        "perks",
        "conditionedBirthrights",
        "capabilities",
        "powerSkills",
        "maneuvers"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "type",
    "name",
    "_id",
    "system"
  ],
  "additionalProperties": true
}

=== jlandic/foundry-fading-suns-4/source/items/species/vorox_eVFX5GyleS0fzGCa.json
{
  "type": "species",
  "name": "vorox",
  "folder": null,
  "system": {
    "slug": "vorox",
    "description": "",
    "size": 7,
    "speed": {
      "twoLegs": 14,
      "fourLegs": 21,
      "sixLegs": 28
    },
    "birthrights": [
      "bite",
      "brutal",
      "huge",
      "no_occult",
      "predatory",
      "sensitive_smell",
      "uncouth"
    ],
    "perks": [
      "smell_danger"
    ],
    "conditionedBirthrights": [
      "noble_claw"
    ],
    "capabilities": [
      [
        "speak_voroxian"
      ]
    ],
    "powerSkills": [],
    "maneuvers": []
  },
  "_id": "eVFX5GyleS0fzGCa",
  "img": "icons/magic/control/silhouette-grow-shrink-tan.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760871251544,
    "modifiedTime": 1760871251544,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!eVFX5GyleS0fzGCa"
}

=== jlandic/foundry-fading-suns-4/source/items/species/human_p9BuG1bXSsPKRGqI.json
{
  "type": "species",
  "name": "human",
  "folder": null,
  "system": {
    "slug": "human",
    "description": "",
    "size": 5,
    "speed": {
      "twoLegs": 10
    },
    "birthrights": [],
    "perks": [],
    "conditionedBirthrights": [],
    "capabilities": [],
    "powerSkills": [],
    "maneuvers": []
  },
  "_id": "p9BuG1bXSsPKRGqI",
  "img": "icons/magic/control/silhouette-grow-shrink-tan.webp",
  "effects": [],
  "flags": {},
  "_stats": {
    "compendiumSource": null,
    "duplicateSource": null,
    "exportSource": null,
    "coreVersion": "13.350",
    "systemId": "fading-suns-4",
    "systemVersion": "0.0.1",
    "createdTime": 1760871251544,
    "modifiedTime": 1760871251544,
    "lastModifiedBy": "ef54fWvGiyPGgegN"
  },
  "ownership": {
    "default": 0,
    "ef54fWvGiyPGgegN": 3
  },
  "sort": 0,
  "_key": "!items!p9BuG1bXSsPKRGqI"
}
